line-length = 120
indent-width = 4

# Skip files in 'templates' directory.
exclude = [
    "templates"
]

[lint]
select = [
    "F", # Pyflakes
    "E", # pycodestyle Errors
    "W", # pycodestyle Warnings
    "D" # pydocstyle
]

ignore = [
    # E203: Whitespace before ':'. See https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#slices
    "E203",
    # D203: 1 blank line required before class docstring -> ignore
    # because conflicts with D211
    "D203",
    # D212: Multi-line docstring summary should start at the first line ->
    # ignore because conflicts with D213
    "D212"
]

[format]
indent-style = "space" # Indent with spaces, rather than tabs
