trigger:
  branches:
    include:
      - main
      - develop      
  paths:
    include:      
      - .pipelines/templates/adf/deploy.yaml
      - .pipelines/variables/app/
      - .pipelines/adf.yaml
      - orchestration_pipeline

name: Build and deploy function app

pool: aib-refbuild

stages:
  - stage: deploytodev
    displayName: Deploy and Create Azure Functions in Dev
    condition: |
      and(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), succeeded())
    variables:
      - template: ./variables/app/common.yaml
      - template: ./variables/app/dev.yaml
    jobs:
      - template: templates/adf/deploy.yaml
        parameters:
          azureServiceConnection: ${{ variables.AzureServiceConnection }}
          artifactName: ${{ variables.BuildArtifactName }}
          environmentToDeploy: ${{ variables.EnvironmentToDeploy }}
          vars: ${{ variables }}
  - stage: deploytotst
    displayName: Deploy and Create Azure Functions in Test
    dependsOn: deploytodev
    condition: |
      and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), succeeded())
    variables:
      - template: ./variables/app/common.yaml
      - template: ./variables/app/tst.yaml
    jobs:
      - template: templates/adf/deploy.yaml
        parameters:
          azureServiceConnection: ${{ variables.AzureServiceConnection }}
          artifactName: ${{ variables.BuildArtifactName }}
          environmentToDeploy: ${{ variables.environmentToDeploy }}
          vars: ${{ variables }}
  - stage: deploytoprd
    displayName: Deploy and Create Azure Functions in Production
    dependsOn: deploytotst
    condition: |
      and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), succeeded())
    variables:
      - template: ./variables/app/common.yaml
      - template: ./variables/app/prd.yaml
    jobs:
      - template: templates/adf/deploy.yaml
        parameters:
          azureServiceConnection: ${{ variables.AzureServiceConnection }}
          artifactName: ${{ variables.BuildArtifactName }}
          environmentToDeploy: ${{ variables.environmentToDeploy }}
          vars: ${{ variables }}
