parameters:
  - name: azureServiceConnection
    type: string
  - name: artifactName
    type: string
  - name: environmentToDeploy
    type: string
  - name: vars
    type: object

jobs:
  - deployment: DeployDatabase
    displayName: Deploy Database
    environment:
      name: ${{ parameters.environmentToDeploy }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              displayName: Download Build Artifacts
              inputs:
                buildType: current
                downloadType: single
                artifactName: ${{ parameters.artifactName }}
                downloadPath: $(System.ArtifactsDirectory)
            - task: AzureCLI@2
              displayName: Deploy Database
              inputs:
                azureSubscription: ${{ parameters.azureServiceConnection }}
                scriptType: pscore
                continueOnError: false
                failOnStandardError: false
                powerShellErrorActionPreference: Stop
                scriptLocation: inlineScript
                inlineScript: |
                  $token=az account get-access-token --resource=https://database.windows.net --query accessToken --output tsv
                  sqlpackage /AccessToken:$token `
                  /TargetServerName:${{ parameters.vars.AzureSQLServerName }}.database.windows.net `
                  /TargetDatabaseName:${{ parameters.vars.AzureSQLServerDBName }} `
                  /Action:Publish `
                  /SourceFile:$(System.ArtifactsDirectory)/${{ parameters.artifactName }}/sql_store/sql_Store/bin/Release/sql_Store.dacpac
