# Copyright (C) Microsoft Corporation.

FROM ubuntu:22.04

# Create a user with user ID 10001 and a group with group ID 10002
# The IDs 10001 and 10002 are non-privileged IDs, and they are chosen arbitrarily.
ARG UID=10001
ARG GID=10002

# Update the package list, install sudo, create a non-root user, and grant password-less sudo permissions
RUN apt update && \
    apt install -y sudo python3 python3-pip jq curl python3.10-venv && \
    addgroup --gid $GID simuser && \
    adduser --uid $UID --gid $GID --disabled-password --gecos "" simuser && \
    echo 'simuser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

RUN sudo apt upgrade -y  && curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash && sudo apt install azure-cli -y

RUN usermod -aG sudo simuser

# Set the non-root user as the default user
USER simuser

WORKDIR {{ parameters.toolchain_output_path }}

# Copy files into the container and set the appropriate permissions
COPY --chown=simuser:simuser ./cognata_simulation_symphony_campaign {{ parameters.toolchain_output_path }}/cognata_simulation_symphony_campaign
COPY --chown=simuser:simuser ./cognata_simulation_proxy {{ parameters.toolchain_output_path }}
RUN chmod -R 755 {{ parameters.toolchain_output_path }}

RUN python3 -m venv metamodel-venv
RUN metamodel-venv/bin/pip install Flask
RUN metamodel-venv/bin/pip install gunicorn

WORKDIR {{ parameters.toolchain_output_path }}
# Expose port {{ parameters.port }} which this simulation proxy listens on.
EXPOSE {{ parameters.port }}
CMD ["{{ parameters.toolchain_output_path }}/metamodel-venv/bin/gunicorn", "--bind", "{{ parameters.host_authority }}:{{ parameters.port }}", "cognata_simulation_proxy:app"]
