name: Upload Azure Login tool cache
on: push

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  upload_tool_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Archive Azure Login tool cache
        run: |
          # Navigate to the runner's tool cache directory
          cd "${{ runner.tool_cache }}/_actions"
          
          # Verify if Azure/login has been cached correctly
          if [ -d "azure/login" ]; then
            echo "Azure/login action found, creating archive."
            tar -czf azure_login_cache.tar.gz azure/login
          else
            echo "Azure/login action not found, exiting."
            exit 1
          fi

      - name: Upload Azure Login cache as artifact
        uses: actions/upload-artifact@v4
        with:
          name: azure-login-cache
          path: ${{ runner.tool_cache }}/_actions/azure_login_cache.tar.gz
