name: Deploy.environment.project

on:
  workflow_dispatch:
    inputs:
        customerOEMsuffix:
          description: "suffix required for customer OEM in lowercase"
          required: true
        Project:
            description: "enter the project name within 5 characters"
            required: true
      
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sub-AVL_DevopsPilot
    
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: |
          cd environment/project
          terraform init

      - name: Plan Terraform changes
        run: |
          cd environment/project
          terraform plan -out=tfplan -var="OEM=${{ github.event.inputs.customerOEMsuffix }}" -var="project=${{ github.event.inputs.Project }}"

      - name: Apply Terraform changes
        run: |
          cd environment/project
          terraform apply -auto-approve tfplan
