name: Deploy.environment.project

on:
  workflow_dispatch:
    inputs:
        customerOEMsuffix:
          description: "suffix required for customer OEM in lowercase"
          required: true
        projectname:
          description: "ente the project name"
          required: true
      
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sub-AVL_DevopsPilot
    
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: |
          cd Archive/archive/project
          terraform init

      - name: Plan Terraform changes
        run: |
          cd Archive/archive/project
          terraform plan -out=tfplan -var="OEM=${{ github.event.inputs.customerOEMsuffix }}" -var="project=${{ github.event.inputs.projectname }}"

      - name: Apply Terraform changes
        run: |
          cd Archive/archive/project
          terraform apply -auto-approve tfplan
