name: Deploy.sdv-tool-chain

on:
  workflow_dispatch:
      
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest #TODO: Discuss and decide on the runner type
    environment: sub-AVL_DevopsPilot
    env:
      TOOlCHAIN_ROOT_PATH: ${{ github.workspace }}/sdv-tool-chain/platform/toolchain
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          pip install yq # yq is used to parse yaml files
          pip install -r $TOOlCHAIN_ROOT_PATH/requirements.txt
          pip install -r $TOOlCHAIN_ROOT_PATH/requirements_test.txt

      - name: Validate Metamodel
        run: python $TOOlCHAIN_ROOT_PATH/src/toolchain_cli.py metamodel validate --from-file  ${{ github.workspace }}/metamodel/avl_sdv_template.yaml --override  ${{ github.workspace }}/metamodel/avl_sdv_template_overrides.yaml

      - name: Run Sdv Tool Chain for Metamodel 
        run: python $TOOlCHAIN_ROOT_PATH/src/toolchain_cli.py metamodel execute --from-file  ${{ github.workspace }}/metamodel/avl_sdv_template.yaml --override  ${{ github.workspace }}/metamodel/avl_sdv_template_overrides.yaml --output-dir  ${{ github.workspace }}/output/metamodel

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload Output Files to file share
        shell: pwsh
        run: |
          $fileShare = "avldevops"

          $customer_OEM_suffix = yq -i '.customer_OEM_suffix' "${{ github.workspace }}/metamodel/avl_sdv_template_overrides.yaml"
          $project_name = yq -i '.project_name' "${{ github.workspace }}/metamodel/avl_sdv_template_overrides.yaml"

          $resource_name_primary_prefix = yq -i '.resource_name_primary_prefix' "${{ github.workspace }}/metamodel/avl_sdv_template_overrides.yaml"
          $resource_name_secondary_prefix = yq -i '.resource_name_secondary_prefix' "${{ github.workspace }}/metamodel/avl_sdv_template_overrides.yaml"
          $resource_name_shared_short = yq -i '.resource_name_shared_short' "${{ github.workspace }}/metamodel/avl_sdv_template_overrides.yaml"
          $environment_stage_short = yq -i '.environment_stage_short' "${{ github.workspace }}/metamodel/avl_sdv_template_overrides.yaml"
          

          $subscription_id = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          $ResourceGroup =  "$($resource_name_primary_prefix)-$($resource_name_secondary_prefix)-$($resource_name_shared_short)-stamp-$($environment_stage_short)-rg-001"
          $storageAccount = "$($resource_name_primary_prefix)$($resource_name_secondary_prefix)$($resource_name_shared_short)$($environment_stage_short)sa"
          $destinationPath = "$($customer_OEM_suffix)/$($project_name)/$($fileShare)"

          $storage_key = 
          az storage account keys list `
            --subscription "$subscriptionID" `
            -g "$ResourceGroup" `
            -n "$storageAccount" `
            --query "[0].value" `
            -o tsv `
            --only-show-errors
          
          az storage file upload-batch `
            --account-name $storageAccount `
            --account-key $storage_key `
            --destination "$fileShare" `
            --destination-path  "$destinationPath"`
            --source "${{ github.workspace }}/output/metamodel"

          az storage file list `
            --account-name $storageAccount `
            --account-key $storage_key `
            --share-name "$fileShare" 
        
