name: Deploy.sdv-tool-chain

on:
  workflow_dispatch:
      
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sub-AVL_DevopsPilot
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          
      - name: Install dependencies
        run: |
          pip install -r ./sdv-tool-chain/platform/toolchain/requirements.txt
          pip install -r ./sdv-tool-chain/platform/toolchain/requirements_test.txt
        working-directory: ${{ github.workspace }}

      - name: Validate Metamodel
        run: python  ${{ github.workspace }}/sdv-tool-chain/platform/toolchain/src/toolchain_cli.py metamodel validate --from-file  ${{ github.workspace }}/metamodel/avl_sdv_template.yaml --override  ${{ github.workspace }}/metamodel/avl_sdv_template_overrides.yaml


      - name: Run Sdv Tool Chain for Metamodel 
        run: python  ${{ github.workspace }}/sdv-tool-chain/platform/toolchain/src/toolchain_cli.py metamodel execute --from-file  ${{ github.workspace }}/metamodel/avl_sdv_template.yaml --override  ${{ github.workspace }}/metamodel/avl_sdv_template_overrides.yaml --output-dir  ${{ github.workspace }}/output/avl_devops_pilot
        working-directory: ${{ github.workspace }}

      - name: Zip the output
        run: zip -r  ./output/avl_devops_pilot.zip /output/avl_devops_pilot
        working-directory: ${{ github.workspace }}
        

      - name: Upload the output
        uses: actions/upload-artifact@v2
        with:
          name: avl_devops_pilot
          path: '${{ github.workspace }}/output/avl_devops_pilot.zip'
        
