name: Upload Azure Login tool cache
on:
  workflow_dispatch:
jobs:
  upload_tool_cache:
    runs-on: ubuntu-22.04
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old" || true
          mkdir -p "${{ runner.tool_cache }}"
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          cd "../_actions"
          ls -la .
        #   tar -czf tool_cache.tar.gz *
      #- name: List tool cache directory
       # run: ls -la "${{ runner.tool_cache }}"
      #- name: Archive tool cache
       # run: |
        #  cd "${{ runner.tool_cache }}"
         # tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ runner.tool_cache }}/tool_cache.tar.gz
