name: Test.infrastructure.shared-stamp
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Choose the environment: d for dev, t for test, p for Prod"
        options:
          - d
          - t
          - p
        required: true

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    #environment: sub-AVL_DevopsPilot
    environment: ${{ github.event.inputs.environment == 'd' && 'sub-AVL_DevopsPilot' || github.event.inputs.environment == 't' && 'sub-DevOpsPilot_Test' }}
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: CheckoutRepo
        uses: actions/checkout@v2
      - name: Deploy shared-stamp
        uses: Azure/arm-deploy@v1
        id: rgDeploy
        with:
          scope: 'subscription'
          region: 'westeurope'
          template: 'infra/shared-stamp/test.json'
  
