name: Run manifest.yaml

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sub-AVL_DevopsPilot
    
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Grant execute permission to manifest.yaml
      run: chmod +x environment/vmss/manifest.yaml

    - name: Run manifest.yaml
      run: |
        cd environment/vmss
        ./manifest.yaml
