name: Deploy.environment.vmss

on:
  workflow_dispatch:
    inputs:
      resource_name:
        description: 'The name of the Azure resource'
        required: true
      location:
        description: 'The Azure region where resources will be deployed'
        required: true
      resource_group_name:
        description: 'The name of the Azure resource group'
        required: true
      vnet:
        description: 'vnet name'
        required: true
      
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sub-AVL_DevopsPilot

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: |
          cd environment/vmss
          terraform init

      - name: Plan Terraform changes
        run: |
          cd environment/vmss
          terraform plan -out=tfplan -var="vnet=${{ github.event.inputs.vnet }}" -var="resource_group_name=${{ github.event.inputs.resource_group_name }}" -var="resource_name=${{ github.event.inputs.resource_name }}" -var="location=${{ github.event.inputs.location }}"

      - name: Apply Terraform changes
        run: |
          cd environment/vmss
          terraform apply -auto-approve tfplan
