name: Run manifest.yaml

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sub-AVL_DevopsPilot
    
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize Terraform
      run: |
        cd environment/vmss
        terraform init

    - name: Plan Terraform changes
      run: |
        cd environment/vmss
        terraform plan -out=tfplan

    - name: Apply Terraform changes
      run: |
        cd environment/vmss
        terraform apply -auto-approve tfplan
