name: Run manifest.yaml

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sub-AVL_DevopsPilot
    
    steps:

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run manifest.yaml
      run: |
        cd environment/vmss
        # Assuming manifest.yaml needs some specific command to execute
        # Replace the placeholder with the actual command needed to run your manifest.yaml script
        # Example: python manifest.yaml
        # Make sure to provide the correct path if manifest.yaml is in a different directory
        ./manifest.yaml
